#!/bin/bash
# check that sssd can connect to active directory
# in light of an instance where sssd went offline because of the machine/AD trust relationship breaking

# nagios setup
UTILS=/usr/lib64/nagios/plugins/utils.sh
if [ -x "${UTILS}" ]; then
        . "${UTILS}"
else   
        echo "ERROR: Cannot find ${UTILS}"
        exit $STATE_UNKNOWN
fi

host=$(/usr/bin/hostname -s)
domain="$1"
online_check=$(/usr/sbin/sssctl domain-status -o $domain | grep status | awk '{print $3}')

if [ "$online_check" != "Online" ]; then
        echo "PROBLEM - $host - $domain - $online_check (sssd/AD)"
        exit $STATE_CRITICAL
fi

echo "OK - $host $domain $online_check (sssd/AD)"

exit $STATE_OK
