#!/bin/bash
# monitor samba / smb shares
# sourced in part from http://www.revpol.com/xymon_samba_script
# assumes that if a specified share is visible in smbstatus -c 
# smb is working as expected

# nagios setup
UTILS=/usr/lib64/nagios/plugins/utils.sh
if [ -x "${UTILS}" ]; then
        . "${UTILS}"
else   
        echo "ERROR: Cannot find ${UTILS}"
        exit $STATE_UNKNOWN
fi

script=$(basename $0)

function debug { # function to enable debug 
	if [ "$debugon" == "yes" ]; then
		$@
	fi
}

function usage {
	echo "$script -e [N] -d"
	echo "-e (mandatory) requires a value for a share to check to ensure it is present"
	echo "-d (optional) enables debug mode"
}

# get the flags
while getopts “e:d” OPTION
do
	case $OPTION in
		 d)
			 debugon="yes"
			 ;;
		 e)
			 expectedavailableshare=$OPTARG
			 ;;
		 ?)
			 usage
			 exit
			 ;;
	 esac
done

if [ -z "$expectedavailableshare" ]; then
	usage
	exit
fi

# most of these variables can be ignored
host=$(/usr/bin/hostname -s)
totalopenedshares=$(smbstatus -S | grep -v "^-\|^$\|Connected at\|^IPC" | sort | cut -d' ' -f1 | wc -l)
availableshares=$(smbstatus -S | grep -v "^-\|^$\|Connected at\|^IPC" | sort | cut -d' ' -f1 | uniq | wc -l)
visibleshares=$(smbstatus -S | grep -v "^-\|^$\|Connected at\|^IPC" | sort | cut -d' ' -f1 | uniq)
totalopenfiles=$(smbstatus -L | grep ^[0-9] | wc -l)
sharecheck=$(smbstatus -S | grep -v "^-\|^$\|Connected at\|^IPC" | sort | cut -d' ' -f1 | uniq | grep "$expectedavailableshare")

debug echo "host = $host | expectedavailableshare = $expectedavailableshare | sharecheck = $sharecheck  | availableshares = $availableshares | totalopenedshares = $totalopenedshares | totalopenfiles = $totalopenfiles"
debug echo ""
debug echo "the available shares are:"
debug echo "visible shares"
debug echo "$visibleshares"
debug echo ""
debug echo "sharecheck variable output:"
debug echo "$sharecheck"
debug echo ""
debug echo "smbstatus output:"
debug smbstatus -S | grep -v "^-\|^$\|Connected at\|^IPC" | sort | cut -d' ' -f1 | uniq
debug echo ""

if [ "$sharecheck" != "$expectedavailableshare" ]; then
	echo "PROBLEM - SMB on $host has the ("$visibleshares") samba shares available but the ($expectedavailableshare) share is expected and not present"
	echo "See https://wiki.tchpc.tcd.ie/doku.php?id=tilda-s02-setup"
	exit $STATE_CRITICAL
fi

echo "OK - SMB on $host has ("$visibleshares") samba shares available, including the ($expectedavailableshare) share as required by this check"

exit $STATE_OK
